sudo: false

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

git:
  depth: 10

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - make deps deps-test

script:
  - go test -race .
  - go test -cover .
