language: go

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - tip

before_install:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -race ./...
  - go test -cover ./...

matrix:
    allow_failures:
        - go: tip

git:
  depth: 10
