ignored = ["github.com/lusis/slack-test"]

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
