################################################################################

# This Makefile generated by GoMakeGen 0.6.1 using next command:
# gomakegen .

################################################################################

.PHONY = fmt deps deps-test test

################################################################################

deps:
	go get -d -v golang.org/x/net/websocket

deps-test:
	go get -d -v github.com/stretchr/testify

test:
	go test -covermode=count .

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

################################################################################
